### ISSUE TITLE
Feature: WebDAV link copy

### ISSUE THREAD

**Issue by EV21** [NastuzziSamy/files_rightclick#15]
As the browser richtclick menu is replaced it is not possible to copy the WebDAV-link of a file.

The link for a file is something like this:
https://cloud.example.com/remote.php/webdav/NiceSong.mp3

Folders have different NC links, but as a bonus it would be nice to provide WebDAV-links also for folders.
https://cloud.example.com/remote.php/webdav/Notes
Usage example with windows-explorer:

![webdav-folder](https://user-images.githubusercontent.com/8345730/39472686-32996362-4d4b-11e8-94d7-bec4ec1db853.png)

**Comment by NastuzziSamy** [comment]
Hey,

I will implement that after adding submenus in the original rightclick menu.
I really find that they are already too many options sometimes

I just released my TODOs: https://github.com/NastuzziSamy/files_rightclick/commit/87b577a2436679420b5f10ade96cc7e89b685499

**Comment by NastuzziSamy** [comment]
@EV21 It will be introduced in the v0.8.2, using submenus (https://github.com/NastuzziSamy/files_rightclick/commit/fbb9eca690e37114d3b7d62535f2849ec15fc96f)

**Comment by NastuzziSamy** [comment]
@EV21 Enjoy https://github.com/NastuzziSamy/files_rightclick/commit/9fc7c829e4c1c34e9f33fcbef4a00fd8b47f48e7 ;)
