### ISSUE TITLE
Please add a changelog

### ISSUE THREAD

**Issue by Schmuuu** [NastuzziSamy/files_rightclick#16]
Hi,

Could you please add  change log to this repository. I really like the many updates for this app and that there is intensive work going on. 
For now however I don't know what features were added or which bugs were fixed, so that I could check out the new features or just look forward updating because of some bugs fixed. 

Would be great! Thanks and keep up the very good work! I love your app ;)

**Comment by NastuzziSamy** [comment]
Hi @Schmuuu,

You are right, my apologies.

Thank you, I think you will enjoy the 0.8.1 update ;)
