### ISSUE TITLE
Uncaught Error in ajax/applications.php:3

### ISSUE THREAD

**Issue by zorn-v** [NastuzziSamy/files_rightclick#17]
PHP Fatal error:  Uncaught Error: Class 'OCP\User' not found in `nextcloud/apps/files_rightclick/ajax/applications.php:3`

You can get it if you run nexcloud without rewrites. For ex. with `php -S localhost:8000`.
I think you should use `OC.generateUrl` here https://github.com/NastuzziSamy/files_rightclick/blob/master/js/files.js#L8
And here too BTW https://github.com/NastuzziSamy/files_rightclick/blob/master/js/script.js#L146

**Comment by zorn-v** [comment]
I created PR https://github.com/NastuzziSamy/files_rightclick/pull/18

**Comment by NastuzziSamy** [comment]
Hey,

Thanks for all, it is now fixed https://github.com/NastuzziSamy/files_rightclick/commit/9fc7c829e4c1c34e9f33fcbef4a00fd8b47f48e7 ;)

**Comment by zorn-v** [comment]
Why you don't use actual "router-controller" ?
You dont need to check if user is logged in and also...
I can make PR if you wish.

**Comment by NastuzziSamy** [comment]
If you know a better way to do it, do not hesitate to PR then
