### ISSUE TITLE
icon-share => icon-shared

### ISSUE THREAD

**Issue by 1ucay** [NastuzziSamy/files_rightclick#19]
Hi, I have problem in menu with "icon-share". I dont know why, but there is not "icon-share" in css, but "icon-shared". Thank you

**Comment by NastuzziSamy** [comment]
Hi !

I don't know why it worked for me haha. It is corrected here: https://github.com/NastuzziSamy/files_rightclick/commit/d9ba1654cd4462eeb442ef83af3655f249f35193

Thx
