### ISSUE TITLE
Strange things with shared folders

### ISSUE THREAD

**Issue by DiGGeR2** [NastuzziSamy/files_rightclick#2]
Thanks for you cool app. But there is a little bug.

- User A share a Folder with user B

- User B, use your app, and select stop sharing this folder (why is this option displayed ? because he don't share this directory) Ok, I'm curious, I click on this option

Result : The folder is no more displayed for user B but when user A check It's allways shared with the user B

**Comment by NastuzziSamy** [comment]
First, thanks for your feedback !

I tried what you report as a bug and i think it's only a feature of Nextcloud, allowing you to stop getting the sharing.

The app only print what Nextcloud should print if you click on dots and add a few options but do not add any sharing option
