### ISSUE TITLE
Changelog on the apps.nextcloud.com

### ISSUE THREAD

**Issue by lachmanfrantisek** [NastuzziSamy/files_rightclick#21]
Hi,

you are releasing new versions so quick, that I always need to go to GitHub to see what is new. (I am using RSS reader for the updates from the apps.nextcloud.com.)

(Thanks for the resolving of the #16 )

Would it be possible to add the changes to the release? (To see it [here](https://apps.nextcloud.com/apps/files_rightclick/releases?platform=13#13) like for example [mail app](https://apps.nextcloud.com/apps/mail/releases?platform=13#13).)

Nothing important but nice-to-have..;-)

Thanks!

**Comment by NastuzziSamy** [comment]
They are no documentation explaining how to publish changelogs.

But don't worry, it will be available for the next release ;)

**Comment by NastuzziSamy** [comment]
@lachmanfrantisek I fanally did it ! \o/
https://apps.nextcloud.com/apps/files_rightclick/releases?platform=15#15

**Comment by lachmanfrantisek** [comment]
@NastuzziSamy Thanks! I've already got the changelog on my feedreader:

![feedreader](https://user-images.githubusercontent.com/20214043/51832146-2df66d80-22f4-11e9-9df2-7e9960eee009.png)
