### ISSUE TITLE
▶ add a class for "▶"

### ISSUE THREAD

**Issue by blackcrack** [NastuzziSamy/files_rightclick#26]
Hi,

can you maybe add a class for "<span style="padding-right: 10px;">▶</span>" 
to have a possible for set a font-size:XXpx; to this class ?
could looking like this : 
```html<span class="arrow" style="padding-right: 10px;">▶</span>```

with this it is able to setting up with smaller size the "▶" via font-size: ;  : 
![screen 00000](https://user-images.githubusercontent.com/7925717/42443190-2044b20e-836d-11e8-9940-3271e5e28863.jpg)

**Comment by NastuzziSamy** [comment]
It will be in the next release. 

Note: I'll define a setting to show the context menu in the current way or in the classical way (left top corner on the cursor by default)

**Comment by blackcrack** [comment]
:+1:  thank you :))))
