### ISSUE TITLE
Can't install from AppStore

### ISSUE THREAD

**Issue by FoXFTW** [NastuzziSamy/files_rightclick#3]
Clicking the install button results in the following curl error:  
```
cURL error 7: Failed to connect to cloud.nastuzzi.fr port 443: No route to host
```

**Comment by nickelfault** [comment]
Same issue here, looks like the server is down.

**Comment by NastuzziSamy** [comment]
Hey everybody, sorry for the issue, the server was actually down.

You can now, from this morning, download it.

**Comment by jonasstaehle** [comment]
I am having the same issue: Enabling this app from Nextcloud apps settings does not give an error but there is no right click menu.  cloud.nastuzzi.fr seems to be available though.

**Comment by NastuzziSamy** [comment]
The application is downloadable here https://apps.nextcloud.com/apps/files_rightclick.

Can you check if, under the files application, js/files_rightclick/script.js is loaded ?

**Comment by jonasstaehle** [comment]
Not sure if i understand correctly. After removing the automatically installed app completely I tried it manually once more:
Move the extracted files into nextcloud/apps/files_rightclick (with correct permissions) and enabled the app as administrator in the "Apps" menu.

But I do not get a right click menu when right clicking on files or folders in chromium or firefox.
There is also no apps/files/js/files_rightclick directory. The script sits in apps/files_rightclick/js/script.js

**Comment by NastuzziSamy** [comment]
What I meant is when you are navigating in /apps/files, in your navigator, can you check if the files_rightclick js script is loaded ?

**Comment by jonasstaehle** [comment]
Oh ok. Yes the script.js from files_rightclick is loaded.

**Comment by jonasstaehle** [comment]
Oh ok.In my navigator the script is in apps -> files_rightclick/js -> script.js
In "apps -> js" no files_rightclick exits.

**Comment by jonasstaehle** [comment]
After upgrading to Nextcloud version 13, the right click app suddenly works :)

**Comment by NastuzziSamy** [comment]
Ok thanks for your feedback.

I will check if it only works with N13 and up..
