### ISSUE TITLE
Norwegion language pack - kan help you.

### ISSUE THREAD

**Issue by jcbdg18** [NastuzziSamy/files_rightclick#32]
Hei.

I am not familiar with git, but i want to help you to get in norwegian langueage pack into files_rightclick. 
In the menu i can see english or german if i click, and the reste of the menu (nextcloud ones) is norwegion.
So, if you want my help, please send me what you need. Is it enough with a .js og .json style file with the translation?

**Comment by NastuzziSamy** [comment]
Hey !

Just copy this files to your langage and PR:
- `l10n/fr.js`
- `l10n/fr.json`

Thanks for your contribution :)

**Comment by jcbdg18** [comment]
Hey.

I attached the to files as no.js and no.json. Hope so you can implement it soon. Thank you!
[Languagepack_norwegian.zip](https://github.com/NastuzziSamy/files_rightclick/files/2768099/Languagepack_norwegian.zip)

**Comment by NastuzziSamy** [comment]
@jcbdg18, thank you.

So I can publish a new release, do you want me to add your files ?
I would prefer if you can fork and commit this two files, so you appear like the contributor for this language support :)

**Comment by jcbdg18** [comment]
I folk and commit the to files to the master branch. Hope that was the right way :-)

**Comment by NastuzziSamy** [comment]
@jcbdg18 are you finished ?

**Comment by apiraino** [comment]
If @jcbdg18 isn't too comfortable using git for a PR, I can take care of it (giving credit where credit is due) :+1:

**Comment by NastuzziSamy** [comment]
@apiraino as I got no anwsers, open a PR 😉
