### ISSUE TITLE
Not Work!!

### ISSUE THREAD

**Issue by Nikolai714** [NastuzziSamy/files_rightclick#33]
Best regards!.. The application is very useful, but unfortunately when you download it in Nextcloud 14.0.3/14.0.4 This is not installed.

Nor can it be installed manually.

Thank you for your time.

Good morning.

**Comment by CodeBrauer** [comment]
The installation needs external resources which are not available..

```
Failed to connect to cloud.nastuzzi.fr port 443: Connection timed out
```

Multiple apps have this problem at the moment:
- https://github.com/NastuzziSamy/files_external_gdrive/issues/32
- https://github.com/NastuzziSamy/files_rightclick/issues/30

**Comment by NastuzziSamy** [comment]
Hey guys, it was simplier for me to upload my apps on my own Nextcloud server but with the time, I know it was a bad idea.

I am now busy but I will release a new version of this app with a Github download link.

Feel sorry about the disturbance.


Note: it is a duplicated issue guys ;)
