### ISSUE TITLE
Right click app Vr 0.10 not working IE 11

### ISSUE THREAD

**Issue by geokh** [NastuzziSamy/files_rightclick#39]
The right click app version 0.10 is not working on Internet Explorer version 11

**Comment by NastuzziSamy** [comment]
@geokh can you give me more information ?

- NC version
- Windows 10 ?
- Do you see something on the browser console ?
- Is only v0.10.0 isn't working ?
- Did it work before ?

Thank you

**Comment by geokh** [comment]
NC version : 15.0.2
Windows 10 ? yes
Do you see something on the browser console ? no it only shows regular right click of the windows
Is only v0.10.0 isn't working ? yes , which was released today.
Did it work before ? yes 
Have you tried in another browser ? Did it work ? yes i tried Chrome and Edge working fine

**Comment by NastuzziSamy** [comment]
@geokh ok thank you, I'll check and release a fix soon :)

**Comment by NastuzziSamy** [comment]
@geokh do you remember the last version of the app working on IE11 ?

**Comment by NastuzziSamy** [comment]
@geokh I just released a new version, it should be good ;)

**Comment by geokh** [comment]
No my friend now it's not working even on Chrome

**Comment by geokh** [comment]
My bad working fine thanks
