### ISSUE TITLE
pdfviewer hidden behind white element when opening pdf via right click menu

### ISSUE THREAD

**Issue by violoncelloCH** [NastuzziSamy/files_rightclick#44]
### to reproduce
1. open a pdf file via right click, read pdf
2. see a white element in front of the pdf viewer (only the top 94 px are visible)
![image](https://user-images.githubusercontent.com/22591354/51438001-96b36980-1ca6-11e9-9c76-6a3393d91a30.png)
when opening the file directly, it's working as expected

**Comment by violoncelloCH** [comment]
Hey, thank you for your fast reply... just updated to v0.10.1 and then the issue appeared... now I updated to v0.10.2 and all is working as expected again... :+1: :)

**Comment by NastuzziSamy** [comment]
Great ! I fixed 2 issues in one update 😉
