### ISSUE TITLE
When multiple items are checked, only the one you right click on is "moved" or "copied"

### ISSUE THREAD

**Issue by BloodyIron** [NastuzziSamy/files_rightclick#5]
When I check (check box on left) multiple items I want to move or copy, I right click on one of the ones checked, tell it the folder to move or copy to, but then it only moves or copies the single file I right clicked on, not the ones I had checked.

This kind of makes right click less useful if this is a present limitation. Can we get this addressed please?

**Comment by NastuzziSamy** [comment]
Hey ! Thank you for the report, i will work on it on the current week

**Comment by BloodyIron** [comment]
Excellent! :D And you're welcome ;)

**Comment by NastuzziSamy** [comment]
@BloodyIron https://github.com/NastuzziSamy/files_rightclick/commit/edeeff21e3582f207452816e2cc17cfe08dafa26 ;)
I will add some options later, like a check or uncheck option

**Comment by BloodyIron** [comment]
Not quite sure how that would address this, how do you see that working? Also, this is closed, does that mean it's implemented, or what?

**Comment by NastuzziSamy** [comment]
@BloodyIron just update your app, check some files/folders and rightclick, you'll see some new options ;)

**Comment by BloodyIron** [comment]
lol! Looks like you handled this way faster than I thought ;D I just didn't see a "commit" in the history here, so I wasn't sure where you are at.

I just updated the app and tested it, and as far as I can tell you have addressed the issue! Thanks for that! :DDD
