### ISSUE TITLE
Simplify and short the language

### ISSUE THREAD

**Issue by EV21** [NastuzziSamy/files_rightclick#9]
I think shorter expressions (like in the 3-dot-menu) are the best solution.

Is it necessary to have all the "this" in the expressions. I think with "this" it is not more clear for the user where he clicked at.

some suggestions
``Open folder`` instead of "Open this folder" - maybe just ``Open`` could be enough
``Share folder`` - maybe just ``Share``
``Open file`` or ``Open``
``Share file`` or ``Share``
``Show picture`` or ``Show``
``Show PDF`` or ``Show``
``Show video`` or ``Show``
``Play`` - (audio player)
``Stop playback`` - (audio player)
``Open in Gallery`` (without the "app" suffix)

**Comment by NastuzziSamy** [comment]
Fixed ;) 

https://github.com/NastuzziSamy/files_rightclick/commit/81499e7237169969bf66fdbb8d9a9883e5ab62cc

**Comment by jonasstaehle** [comment]
Proposed shortening changes for German language:

    "Open folder" : "Ordner öffnen",
    "Open file" : "Datei öffnen",
    "Open in new tab" : "In neuem Tab öffnen",
    "Edit file" : "Datei bearbeiten",
    "Read PDF" : "PDF anzeigen",
    "See picture" : "Bild anzeigen",
    "Open in Gallery" : "In Galerie App öffnen",
    "Play" : "Wiedergabe starten",
    "Stop playback" : "Stoppe Wiedergabe",
    "Watch" : "Video starten",
    "Share folder" : "Ordner teilen",
    "Share file" : "Datei teilen",
    "Select" : "Markieren",
    "Unselect" : "Markierung aufheben"
